// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $easter_egg_index from "./routes/easter_egg/index.tsx";
import * as $frase_frase_ from "./routes/frase/[frase].tsx";
import * as $frase_index from "./routes/frase/index.tsx";
import * as $index from "./routes/index.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $Egg from "./islands/Egg.tsx";
import * as $Start from "./islands/Start.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/easter_egg/index.tsx": $easter_egg_index,
    "./routes/frase/[frase].tsx": $frase_frase_,
    "./routes/frase/index.tsx": $frase_index,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/Counter.tsx": $Counter,
    "./islands/Egg.tsx": $Egg,
    "./islands/Start.tsx": $Start,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
